# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Inject GitHub Secrets and Variables into index.html
        run: |
          sed -i "s|YOUR_BACKEND_URL|${{ secrets.BACKEND_URL }}|g" index.html
          sed -i "s|YOUR_BOT_API_URL|${{ secrets.BOT_API_URL }}|g" index.html
          sed -i "s|YOUR_FIREBASE_DB_URL|${{ secrets.FIREBASE_DB_URL }}|g" index.html
          sed -i "s|YOUR_ADMIN_EMAIL|${{ vars.ADMIN_EMAIL }}|g" index.html
          sed -i "s|YOUR_DOMAIN|${{ vars.MAIL_DOMAIN }}|g" index.html
          sed -i "s|YOUR_DRIVE_LINK|${{ vars.APP_DRIVE_LINK }}|g" index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
